name: "Governance Check"

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read        # Necessário para o checkout
  pull-requests: write  # Necessário para comentar na PR

jobs:
  flow-guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Branch Flow
        uses: Malnati/flow-check@v2.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          custom_template: ".github/workflows/flow-check.md"
